version: '3.8'

services:
    entity-analytics:
        build: ./
        env_file: .env
        command: streamlit run app.py --server.port 8051 --server.address=0.0.0.0
        ports:
            - 8051:8051
        image: entity-analytics:latest